language: php

php: [5.3]

before_script:
  - composer self-update
  - composer install
  # Generate the koharness Kohana default application
  - vendor/bin/koharness

# Run the specs against the koharnessed application in /tmp/koharness
script: vendor/bin/phpspec
